server:
    port: 8082
    servlet:
        context-path: /roommeeting

spring:
    datasource:
        url: jdbc:postgresql://172.17.0.3:5432/postgres
        username: postgres
        password: 123456
    jpa:
        show-sql: true
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        generate-ddl: true
        hibernate:
            ddl-auto: update
